# Generated by Django 3.2.6 on 2021-08-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=50, null=True, verbose_name='fullname')),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
                ('ContactNo', models.DecimalField(decimal_places=0, default='', max_digits=11, verbose_name='phone Number')),
                ('Username', models.CharField(max_length=20, verbose_name='username')),
                ('Password', models.CharField(default='', max_length=15)),
                ('Email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='requesttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='fullname')),
                ('Purpose', models.CharField(choices=[('Binyag', 'Binyag'), ('Kumpil', 'Kumpil'), ('Komunyon', 'Komunyon'), ('Kumpisal', 'Kumpisal'), ('Kasal', 'Kasal'), ('Blessing', 'Blessing'), ('Misa ng Patay', 'Misa ng Patay')], default='', max_length=15, verbose_name='Purpose')),
                ('Date', models.DateField(default='')),
                ('Details', models.CharField(max_length=50, verbose_name='Additional Details')),
                ('Time', models.TimeField(default='')),
                ('Status', models.TextField(choices=[('Accept', 'Accept'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True)),
            ],
        ),
    ]
